// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.EFCore;

#nullable disable

namespace LibraryOrganizerAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231127083740_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Model.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorName = "Fyodor Dostoyevski"
                        },
                        new
                        {
                            AuthorID = 2,
                            AuthorName = "Adolf Hitler"
                        },
                        new
                        {
                            AuthorID = 3,
                            AuthorName = "Lev Tolstoy"
                        });
                });

            modelBuilder.Entity("Entity.Model.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("AdressColumn")
                        .HasColumnType("int");

                    b.Property<string>("AdressCorridor")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("AdressRow")
                        .HasColumnType("int");

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AdressColumn = 1,
                            AdressCorridor = "A",
                            AdressRow = 1,
                            AuthorID = 1,
                            BookName = "Suç ve Ceza",
                            CategoryID = 1
                        },
                        new
                        {
                            BookID = 2,
                            AdressColumn = 1,
                            AdressCorridor = "A",
                            AdressRow = 2,
                            AuthorID = 2,
                            BookName = "Kavgam",
                            CategoryID = 2
                        },
                        new
                        {
                            BookID = 3,
                            AdressColumn = 2,
                            AdressCorridor = "A",
                            AdressRow = 2,
                            AuthorID = 3,
                            BookName = "İnsan Ne İle Yaşar",
                            CategoryID = 3
                        });
                });

            modelBuilder.Entity("Entity.Model.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Roman"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Savaş"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Hikaye"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
